config/routes.rb
Rails.application.routes.draw do
  resources :edges
  resources :tokens
  resources :websites
  root 'websites#homepage'
  get '/search', to: 'edges#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/edge.rb
class Edge < ApplicationRecord
    belongs_to :website
    belongs_to :token

    validates_uniqueness_of :token, scope: [:website]
end

app/models/token.rb
class Token < ApplicationRecord
    has_many :edges
    validates :value, presence: true, uniqueness: true
end

app/models/website.rb
class Website < ApplicationRecord
    has_many :edges
    validates :url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/edges_controller.rb
class EdgesController < ApplicationController
  before_action :set_edge, only: [:show, :edit, :update, :destroy]

  # GET /edges
  # GET /edges.json
  def index
    @edges = Edge.all.order(:quantity)
  end

  # GET /edges/1
  # GET /edges/1.json
  def show
  end

  # GET /edges/new
  def new
    @edge = Edge.new
  end

  # GET /edges/1/edit
  def edit
  end

  # POST /edges
  # POST /edges.json
  def create
    @edge = Edge.new(edge_params)

    respond_to do |format|
      if @edge.save
        format.html { redirect_to @edge, notice: 'Edge was successfully created.' }
        format.json { render :show, status: :created, location: @edge }
      else
        format.html { render :new }
        format.json { render json: @edge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /edges/1
  # PATCH/PUT /edges/1.json
  def update
    respond_to do |format|
      if @edge.update(edge_params)
        format.html { redirect_to @edge, notice: 'Edge was successfully updated.' }
        format.json { render :show, status: :ok, location: @edge }
      else
        format.html { render :edit }
        format.json { render json: @edge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /edges/1
  # DELETE /edges/1.json
  def destroy
    @edge.destroy
    respond_to do |format|
      format.html { redirect_to edges_url, notice: 'Edge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search

    @tokens = edge_params['q'].split

    @searchedToken = []

    @tokens.each do |searchedWord|
      Token.where("value like?", "%#{searchedWord.downcase}%").each do |token|
        @searchedToken.push(token)
      end
    end

    @results = Edge.where(:token => @searchedToken).order(quantity: :desc)

    @tempResultWebsites = @results.map do |result|
      if result.website != nil
        result.website.url
      else
        nil
      end
    end.uniq

    @resultWebsites = []

    @tempResultWebsites.each do |website|
      if website != nil
        @resultWebsites.push(website)
      end
    end

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_edge
      @edge = Edge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def edge_params
      params.fetch(:edge, {})
      params.permit(:q, :utf8, :commit)
    end
end

app/controllers/tokens_controller.rb
class TokensController < ApplicationController
  before_action :set_token, only: [:show, :edit, :update, :destroy]

  # GET /tokens
  # GET /tokens.json
  def index
    @tokens = Token.all
  end

  # GET /tokens/1
  # GET /tokens/1.json
  def show
  end

  # GET /tokens/new
  def new
    @token = Token.new
  end

  # GET /tokens/1/edit
  def edit
  end

  # POST /tokens
  # POST /tokens.json
  def create
    @token = Token.new(token_params)

    respond_to do |format|
      if @token.save
        format.html { redirect_to @token, notice: 'Token was successfully created.' }
        format.json { render :show, status: :created, location: @token }
      else
        format.html { render :new }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tokens/1
  # PATCH/PUT /tokens/1.json
  def update
    respond_to do |format|
      if @token.update(token_params)
        format.html { redirect_to @token, notice: 'Token was successfully updated.' }
        format.json { render :show, status: :ok, location: @token }
      else
        format.html { render :edit }
        format.json { render json: @token.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tokens/1
  # DELETE /tokens/1.json
  def destroy
    @token.destroy
    respond_to do |format|
      format.html { redirect_to tokens_url, notice: 'Token was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_token
      @token = Token.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def token_params
      params.require(:token).permit(:value)
    end
end

app/controllers/websites_controller.rb
class WebsitesController < ApplicationController
  before_action :set_website, only: [:show, :edit, :update, :destroy]

  # GET /websites
  # GET /websites.json
  def index
    @websites = Website.all
  end

  # GET /websites/1
  # GET /websites/1.json
  def show
  end

  # GET /websites/new
  def new
    @website = Website.new
  end

  # GET /websites/1/edit
  def edit
  end

  # POST /websites
  # POST /websites.json
  def create
    @website = Website.new(website_params)

    respond_to do |format|
      if @website.save
        format.html { redirect_to @website, notice: 'Website was successfully created.' }
        format.json { render :show, status: :created, location: @website }
        fetchSingleWebsite(@website.url)
      else
        format.html { render :new }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /websites/1
  # PATCH/PUT /websites/1.json
  def update
    respond_to do |format|
      if @website.update(website_params)
        format.html { redirect_to @website, notice: 'Website was successfully updated.' }
        format.json { render :show, status: :ok, location: @website }
      else
        format.html { render :edit }
        format.json { render json: @website.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /websites/1
  # DELETE /websites/1.json
  def destroy
    @website.destroy
    respond_to do |format|
      format.html { redirect_to websites_url, notice: 'Website was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def fetchSingleWebsite(base_url)
    if Website.all.count > 100
      return
    end
    # fetches page
    require 'open-uri'

    begin
      page = Nokogiri::HTML(open(base_url))
    rescue
      return
    end

    if page != nil
      @website = Website.create(:url => base_url)

      temp_hrefs = page.css('a').map { |link| link.attribute('href') }
      hrefs = []
      temp_hrefs.each do |link|
        if link != nil
          hrefs.push(link.value)
        end
      end

      tokens = page.css('div').text.split
      tokens = tokens.select {|token| token.length >= 3 and token.length <= 10}
      tokens  = tokens.map { |token| token.downcase }

      tokens.each do |token|
        @token = Token.find_by_value(token)

        if @token != nil

        else
          @token = Token.create(:value => token)
        end

        newEdge = Edge.new()
        newEdge.token = @token
        newEdge.website = @website
        newEdge.save

        if newEdge.errors.full_messages.count != 0
          toModifyEdge = Edge.where(:token => @token, :website => @website).first
          if toModifyEdge != nil
            toModifyEdge.quantity += 1
            toModifyEdge.save
          end
        end
      end

      hrefs.each do |href|
        if Website.where(:url => href).count == 0
          if href.include?('http')
            puts "Crawling for: " + href
            fetchSingleWebsite(href)
          end
        end
      end
    end
  end

  def homepage
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_website
      @website = Website.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def website_params
      params.require(:website).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/edges_helper.rb
module EdgesHelper
end

app/helpers/tokens_helper.rb
module TokensHelper
end

app/helpers/websites_helper.rb
module WebsitesHelper
end

app/views/edges/_form.html.erb
<%= form_with(model: edge, local: true) do |form| %>
  <% if edge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(edge.errors.count, "error") %> prohibited this edge from being saved:</h2>

      <ul>
      <% edge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/edges/edit.html.erb
<h1>Editing Edge</h1>

<%= render 'form', edge: @edge %>

<%= link_to 'Show', @edge %> |
<%= link_to 'Back', edges_path %>

app/views/edges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Edges</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @edges.each do |edge| %>
      <tr>
        <td><%= link_to 'Show', edge %></td>
        <td><%= link_to 'Edit', edit_edge_path(edge) %></td>
        <td><%= link_to 'Destroy', edge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Edge', new_edge_path %>

app/views/edges/new.html.erb
<h1>New Edge</h1>

<%= render 'form', edge: @edge %>

<%= link_to 'Back', edges_path %>

app/views/edges/search.html.erb
<h1>Hoogle Search Result</h1>
<tbody>
  <ul>
    <% @resultWebsites.each do |result| %>
      <li><%= link_to result, result %></li>
    <% end %>
  </ul>
</tbody>

app/views/edges/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_edge_path(@edge) %> |
<%= link_to 'Back', edges_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hoogle</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tokens/_form.html.erb
<%= form_with(model: token, local: true) do |form| %>
  <% if token.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(token.errors.count, "error") %> prohibited this token from being saved:</h2>

      <ul>
      <% token.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :token_value %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tokens/edit.html.erb
<h1>Editing Token</h1>

<%= render 'form', token: @token %>

<%= link_to 'Show', @token %> |
<%= link_to 'Back', tokens_path %>

app/views/tokens/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Tokens</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tokens.each do |token| %>
      <tr>
        <td><%= token.value %></td>
        <td><%= link_to 'Show', token %></td>
        <td><%= link_to 'Edit', edit_token_path(token) %></td>
        <td><%= link_to 'Destroy', token, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Token', new_token_path %>

app/views/tokens/new.html.erb
<h1>New Token</h1>

<%= render 'form', token: @token %>

<%= link_to 'Back', tokens_path %>

app/views/tokens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @token.value %>
</p>

<%= link_to 'Edit', edit_token_path(@token) %> |
<%= link_to 'Back', tokens_path %>

app/views/websites/_form.html.erb
<%= form_with(model: website, local: true) do |form| %>
  <% if website.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(website.errors.count, "error") %> prohibited this website from being saved:</h2>

      <ul>
      <% website.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, id: :website_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/websites/edit.html.erb
<h1>Editing Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Show', @website %> |
<%= link_to 'Back', websites_path %>

app/views/websites/homepage.html.erb
<p id="notice"><%= notice %></p>

<h1>Hoogle</h1>

<%= form_tag("/search", method: "get") do %>
<%= label_tag(:q, "Search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>
<br>

app/views/websites/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Websites</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @websites.each do |website| %>
      <tr>
        <td><%= website.url %></td>
        <td><%= link_to 'Show', website %></td>
        <td><%= link_to 'Edit', edit_website_path(website) %></td>
        <td><%= link_to 'Destroy', website, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Website', new_website_path %>

app/views/websites/new.html.erb
<h1>New Website</h1>

<%= render 'form', website: @website %>

<%= link_to 'Back', websites_path %>

app/views/websites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @website.url %>
</p>

<%= link_to 'Edit', edit_website_path(@website) %> |
<%= link_to 'Back', websites_path %>